---
validators:
  description: "Model Validators"
  options:
    - name: detect_pii
      description: ""
      enabled: true
    - name: detect_gibberish
      description: ""
      enabled: true
    - name: detect_toxicity
      description: ""
      enabled: true
    - name: detect_prompt_injection
      description: ""
      enabled: true
    - name: ban_substrings
      description: ""
      enabled: true
    - name: detect_secrets
      description: ""
      enabled: true
    - name: detect_relevance
      description: ""
      enabled: true
    - name: detect_factual_consistency
      description: ""
      enabled: true
